### ISSUE TITLE
PBS and POD

### ISSUE THREAD

**Issue by aphecetche** [AnarManafov/PoD#5]
Hi Anar,

How are you ?

I'm trying to setup a test PoD cluster on an existing PBS farm, and I'm running in a couple of issues. 

First, that PBS does not define TMPDIR, so I have to define it myself (in my .profile, because if I put it only in ~/.PoD/user_worker_env.sh it's not working... OK, just to mention it, it's not blocker.

Second, and more serious, is that the worker jobs are now starting but exit almost immediately. The beginning of the log says:

working directory:  /scratch/aliced/aphecete/tmp/PoD_Kbh1SSHE4V

Writing files in node's directory  /scratch/aliced/aphecete/tmp/PoD_Kbh1SSHE4V
cp: cannot stat `/users/aliced/aphecete/.PoD/wrk/pod-worker': No such file or directory
gzip: stdin has flags 0x8d -- not supported
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
tail: write error: Broken pipe
/scratch/aliced/aphecete/tmp/PoD_Kbh1SSHE4V/PoDWorker.sh: line 320: lockfile: command not found

Any idea what is it that I'm doing wrong ;-) ?

Thanks,

**Comment by AnarManafov** [comment]
Hey man,

apologies for the much delay.

can you please start PoD server and then pack ~/.PoD directory and send it on my email?

**Comment by aphecetche** [comment]
Hi Anar,

Sorry for the late answer.

The thing is that I changed my .PoD to get it working (I now define the TMPDIR in my .bashrc and like that it is working). 

I'll get it back to the non-working version and send it to you, but it might take a couple of days before I can do that.

Regard,s

**Comment by aphecetche** [comment]
Hi Anar,

In fact, I won't have time to reproduce the issue, as I've moved to a HTCondor cluster in the mean time (where things are working just fine ;-) ).

Sorry about that,

Regards,

**Comment by AnarManafov** [comment]
Absolutely no problem, man.
Ping me if you need my help.
